export const caseStudiesData = [
  {
    id: 1,
    title: "NSM Training & Consultancy - CPD Member Case Study",
    date: "05/09/25",
    bgGradient: "from-purple-600 via-purple-500 to-pink-500",
    decorativeElements: "magnifying-glass",
    image: "/caseStudy1.png",
  },
  {
    id: 2,
    title: "CFE Certification - CPD Member Case Study",
    date: "05/09/25",
    bgGradient: "from-blue-600 via-blue-500 to-indigo-600",
    decorativeElements: "question-marks",
    image: "/caseStudy2.png",
  },
  {
    id: 3,
    title: "CIMA Care - CPD Member Case Study",
    date: "05/09/25",
    bgGradient: "from-cyan-400 via-blue-500 to-blue-600",
    decorativeElements: "lightbulb",
    image: "/caseStudy3.png",
  },
  {
    id: 4,
    title: "Health AI CPD - Member Case Study",
    date: "05/09/25",
    bgGradient: "from-orange-500 via-red-500 to-pink-500",
    decorativeElements: "tools",
    image: "/caseStudy4.png",
  },
  {
    id: 5,
    title: "IFRS Lab - CPD Member Case Study",
    date: "05/09/25",
    bgGradient: "from-orange-600 via-orange-500 to-yellow-500",
    decorativeElements: "magnifying-glass-alt",
    image: "/caseStudy5.png",
  },
  {
    id: 6,
    title: "Bolster Systems - CPD Member Case Study",
    date: "05/09/25",
    bgGradient: "from-blue-600 via-purple-600 to-pink-500",
    decorativeElements: "geometric-shapes",
    image: "/caseStudy1.png",
  },
];
