export const DirectoryCardInfo = [
  {
    name: "Alice Johnson",
    role: "Frontend Developer",
    level: "FCPD",
    country: "United States",
    date: "Joined Jan 2023",
    status: "Active",
  },
  {
    name: "Marcus Lee",
    role: "UI/UX Designer",
    level: "ACPD",
    country: "Canada",
    date: "Joined Aug 2022",
    status: "Active",
  },
  {
    name: "Sophia Martinez",
    role: "Project Manager",
    level: "FCPD",
    country: "Spain",
    date: "Joined Mar 2021",
    status: "Active",
  },
  {
    name: "David Kim",
    role: "Full Stack Engineer",
    level: "SCPD",
    country: "South Korea",
    date: "Joined Nov 2020",
    status: "Active",
  },
  {
    name: "Emma Brown",
    role: "Data Scientist",
    level: "ACPD",
    country: "United Kingdom",
    date: "Joined Jul 2023",
    status: "Active",
  },
];
