export const plans = [
  {
    id: "SCPD",
    name: "Standard Certification",
    type: "SCPD - Standard Certification",
    description: "Entry-level recognition for structured learning.",
    features: [
      "300-500 word reflection",
      "1 year certificate validity",
      "5% audit rate",
    ],
    cta: "Choose SCPD",
    popular: true,
    price: "50",
    yearlyPrice: "40",
    period: "Monthly",
  },
  {
    id: "ACPD",
    name: "Advanced Certification",
    type: "ACPD - Standard Certification",
    description: "Mid-level recognition for applied learning.",
    features: [
      "800-1200 word reflection",
      "2 year certificate validity",
      "Portfolio required",
    ],
    cta: "Choose ACPD",
    popular: true,
    price: "50",
    yearlyPrice: "40",
    period: "Monthly",
  },
  {
    id: "FCPD",
    name: "Fellow Certification",
    type: "FCPD - Standard Certification",
    description: "Highest recognition for leadership impact.",
    features: [
      "1500-2000 word reflection",
      "3 year certificate validity",
      "Leadership evidence required",
    ],
    cta: "Choose FCPD",
    popular: true,
    price: "50",
    yearlyPrice: "40",
    period: "Monthly",
  },
];

export const CoursePlans = [
  {
    name: "Starter",
    description: "Perfect for small training providers",
    price: "299",
    yearlyPrice: "239",
    period: "per month",
    features: [
      "Up to 5 training programmes",
      "Basic accreditation review",
      "Public directory listing",
      "Digital certificates",
      "Email support",
      "QR verification",
      "Basic analytics",
    ],
    traningNumber: "1–5 trainings",
    isPopular: false,
  },
  {
    name: "Growth",
    description: "Ideal for growing organizations",
    price: "499",
    yearlyPrice: "399",
    period: "per month",
    features: [
      "Up to 10 training programmes",
      "Priority accreditation review",
      "Enhanced directory listing",
      "Branded certificates",
      "Priority email support",
      "QR verification",
      "Advanced analytics",
      "Custom branding",
    ],
    traningNumber: "6–10 trainings",
    isPopular: false,
  },
  {
    name: "Scale",
    description: "For established training providers",
    price: "899",
    yearlyPrice: "719",
    period: "per month",
    features: [
      "Up to 25 training programmes",
      "Fast-track review (5 days)",
      "Premium directory placement",
      "White-label certificates",
      "Phone & email support",
      "QR verification",
      "Comprehensive analytics",
      "API access",
      "Dedicated account manager",
    ],
    traningNumber: "11–25 trainings",
    isPopular: true,
  },
  {
    name: "Enterprise",
    description: "For large organizations",
    price: "1499",
    yearlyPrice: "1199",
    period: "per month",
    features: [
      "Up to 50 training programmes",
      "Express review (3 days)",
      "Featured directory listing",
      "Fully branded certificates",
      "24/7 priority support",
      "QR verification",
      "Real-time analytics",
      "Full API access",
      "Dedicated success manager",
      "Custom integrations",
    ],
    traningNumber: "26–50 trainings",
    isPopular: false,
  },
  {
    name: "Enterprise+",
    description: "Unlimited scale solution",
    price: "Custom",
    yearlyPrice: "Custom",
    period: "per month",
    features: [
      "Unlimited training programmes",
      "Same-day review available",
      "Premium directory features",
      "Complete white-labelling",
      "Dedicated support team",
      "Advanced QR features",
      "Custom analytics dashboard",
      "Enterprise API",
      "Implementation support",
      "SLA guarantees",
      "Custom compliance features",
    ],
    traningNumber: "51+ trainings",
    isPopular: false,
  },
];
